name: Main Workflow

on:
  push:
    branches:
      - main
      
permissions:
  checks: write


jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - uses: actions/checkout@v4
      